routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'UserController@profile')->name('profile');

Route::group(['middleware' => 'auth'], function(){
	Route::resources([
	    'noticias' 	=> 'NoticiaController',
	    'users'		=> 'UserController',
	]);
});

app/Noticias.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Noticias extends Model
{
    //
}

app/Http/Controllers/NoticiaController.php
<?php

namespace App\Http\Controllers;

use App\Noticias;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\Console\Input\Input;

class NoticiaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticias = Noticias::all();

        return view('noticias.index',[
            'noticias' => $noticias,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('noticias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = array(
            'titulo'    => 'required',
            'extracto'  => 'required',
            'detalle'   => 'required',
            'fecha'     => 'required',
        );

        if ($request->hasFile('imagen')){
            $filenameWithExt = $request->file('imagen')->getClientOriginalName();
            $filename = pathinfo($filenameWithExt,PATHINFO_FILENAME);
            $extension = $request->file('imagen')->getClientOriginalExtension();
            $fileNameToStore = date('Y-m-d_H-i-s') . '_' . uniqid() . '_noticia' . '.' .$extension;
            request()->imagen->move(public_path('imagenes/noticias/'), $fileNameToStore);
        } else {
            $fileNameToStore = "dummy-image.png";
        }

        $validator = Validator::make([
            'titulo' => $request->titulo,
            'extracto' => $request->extracto,
            'detalle' => $request->detalle,
            'fecha' => $request->fecha,
        ], $rules);

        if ($validator->fails()) {
            return Redirect::to('noticias/create')
                ->withErrors($validator);
        } else {
            $noticia = new Noticias;
            $noticia->titulo    = Input::get('titulo');
            $noticia->extracto  = Input::get('extracto');
            $noticia->detalle   = Input::get('detalle');
            $noticia->fecha     = Input::get('fecha');
            $noticia->imagen    = $fileNameToStore;
            $noticia->save();

            Session::flash('message', '¡Noticia creada exitosamente!');
            return Redirect::to('noticias');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $noticia = Noticias::find($id);
        return view('noticias.show',[
            'noticia' => $noticia,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $noticia = Noticias::find($id);
        return view('noticias.edit',[
            'noticia' => $noticia,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Noticias  $noticias
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = array(
            'titulo'    => 'required',
            'extracto'  => 'required',
            'detalle'   => 'required',
            'fecha'     => 'required',
        );

        $validator = Validator::make([
            'titulo' => $request->titulo,
            'extracto' => $request->extracto,
            'detalle' => $request->detalle,
            'fecha' => $request->fecha,
        ], $rules);

        if ($validator->fails()) {
            return Redirect::to('noticias/' . $id . '/edit')
                ->withErrors($validator);
        } else {
            $noticia            = Noticias::find($id);
            $noticia->titulo    = $request->titulo;
            $noticia->extracto  = $request->extracto;
            $noticia->detalle   = $request->detalle;
            $noticia->fecha     = $request->fecha;
            if ($request->hasFile('imagen')){
                $filenameWithExt = $request->file('imagen')->getClientOriginalName();
                $filename = pathinfo($filenameWithExt,PATHINFO_FILENAME);
                $extension = $request->file('imagen')->getClientOriginalExtension();
                $fileNameToStore = date('Y-m-d_H-i-s') . '_' . uniqid() . '_noticia' . '.' .$extension;
                request()->imagen->move(public_path('imagenes/noticias/'), $fileNameToStore);
                $noticia->imagen = $fileNameToStore;
            }
            $noticia->save();

            Session::flash('message', '¡Noticia actualizada exitosamente!');
            return Redirect::to('noticias');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Noticias  $noticias
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $noticia = Noticias::find($id);
        $noticia->delete();

        Session::flash('message', '¡Noticia eliminada exitosamente!');
        return Redirect::to('noticias');
    }
}

resources/views/noticias/create.blade.php
@extends('adminlte::page')

@section('title', 'Noticias')

@section('content_header')
    <h1>Crear Noticia</h1>
@stop

@section('content')
@if(isset($message))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $message }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Crear una Noticia</h3>
		</div>
		<form role="form" method="POST" action="{{ route('noticias.store') }}" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="titulo">Titulo de la Noticia</label>
					<input
						name="titulo"
						type="text"
						class="form-control"
						id="titulo"
						placeholder="Ingresa el Titulo de la Noticia"
						required
					>
				</div>
				<div class="form-group">
					<label for="detalle">Detalle de la Noticia</label>
					<textarea
						name="detalle"
						type="textarea"
						class="form-control"
						id="detalle"
						placeholder="Ingresa el Detalle de la Noticia"
						required
					></textarea>
				</div>
				<div class="form-group">
					<label for="fecha">Fecha de la Noticia</label>
					<input
						name="fecha"
						type="date"
						class="form-control"
						id="fecha"
					>
				</div>
				<div class="form-group">
					<label for="imagen">Imagen de la Noticia</label>
					<input
						name="imagen"
						type="file"
						class="form-control"
						id="imagen"
					>
				</div>
			</div>
			<div class="box-footer">
				<button type="submit" class="btn btn-success">Crear Noticia</button>
				<a class="btn btn-secondary" href="javascript:history.back()">Volver</a>
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/noticias/edit.blade.php
@extends('adminlte::page')

@section('title', 'Noticias')

@section('content_header')
    <h1>Editar Noticia</h1>
@stop

@section('content')
@if(isset($message))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $message }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="row">
			<div class="box-header with-border col-8 align-left">
				<h3 class="box-title">Actualizar Noticia</h3>
			</div>
		</div>
		<form role="form" method="POST" action="{{ route('noticias.update', $noticia) }}" enctype="multipart/form-data">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="titulo">Titulo</label>
					<input
						name="titulo"
						type="text"
						class="form-control"
						id="titulo"
						placeholder="Ingresa el titulo"
						value="{{ $noticia->titulo }}"
					>
				</div>
				<div class="form-group">
					<label for="extracto">Extracto</label>
					<input
						name="extracto"
						type="text"
						class="form-control"
						id="extracto"
						placeholder="Ingresa el extracto"
						value="{{ $noticia->extracto }}"
					>
				</div>
				<div class="form-group">
					<label for="detalle">Detalle</label>
					<input
						name="detalle"
						type="text"
						class="form-control"
						id="detalle"
						placeholder="Ingresa el detalle"
						value="{{ $noticia->detalle }}"
					>
				</div>
				<div class="form-group">
					<label for="fecha">Fecha</label>
					<input
						name="fecha"
						type="date"
						class="form-control"
						id="fecha"
						placeholder="Ingresa la fecha"
						value="{{ $noticia->fecha }}"
					>
				</div>
				<div class="form-group">
					<label for="imagen">Imagen de la Noticia</label>
					<input name="imagen" type="file" id="imagen">
				</div>
			</div>
			<div class="box-footer p-2">
				<button type="submit" class="btn btn-success">Actualizar</button>
			</div>
		</form>
	</div>
</div>
@endsection

resources/views/noticias/index.blade.php
@extends('adminlte::page')

@section('title', 'Noticias')

@section('content_header')
    <h1>Noticias</h1>
@stop

@section('content')
@if(isset($message))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $message }} </h4>
	</div>
@endif

<div class="container">
	@if(isset($noticias))
		@foreach($noticias as $noticia)
			<a href="{{ route('noticias.show', $noticia) }}">
				<div class="row border bg-secondary rounded" style="margin-left: 10px; margin-right: 10px; margin-bottom: 10px;">
					<div class="col-12">
						<div class="row">
							<div class="col-4 align-middle">
								<img src="/imagenes/noticias/{{$noticia->imagen}}" alt="Noticia-{{$noticia->id}}" class="img-fluid rounded"/>
							</div>
							<div class="col-5">
								<h5 class="text-primary">{{ $noticia->titulo }}</h5>
								<p>{{ $noticia->extracto }}</p>
							</div>
							<div class="col-3">
								<small>{{ $noticia->fecha }}</small>
							</div>
						</div>
					</div>
				</div>
			</a>
		@endforeach
	@else
		<div class="card text-center">
	      	<div class="card-body">
	        	<h5 class="card-title">No existen noticias.</h5>
	      	</div>
    	</div>
	@endif
</div>
@endsection

resources/views/noticias/show.blade.php
@extends('adminlte::page')

@section('title', $noticia->titulo)

@section('content_header')
    <h1>{{ $noticia->titulo }}</h1>
@stop

@section('content')
@if(isset($message))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $message }} </h4>
	</div>
@endif

<div class="container">
	<div class="container">
		<div class="d-flex row justify-content-center">
			<div class="card">
				<div class="row no-gutters">
					<div class="col-md-4">
						<img src="/imagenes/noticias/{{$noticia->imagen}}" class="card-img" alt="Noticia-{{$noticia->id}}">
					</div>
					<div class="col-md-8">
						<div class="card-body">
							<h5 class="card-title">{{ $noticia->titulo }}</h5>
							<p class="card-text">{{ $noticia->detalle }}</p>
							<p class="card-text"><small class="text-muted">{{ $noticia->fecha }}</small></p>
							<a href="{{ route('noticias.edit', $noticia) }}" type="button" class="btn btn-success">Editar Noticia</a>
							<form method="POST" action="{{ route('noticias.destroy', $noticia) }}">
								{{ method_field('DELETE') }}
								{{ csrf_field() }}
								<button type="submit" class="btn btn-danger">Eliminar Noticia</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection